### ISSUE TITLE
slice lists

### ISSUE THREAD

**Issue by kallewesterling** [DHRI-Curriculum/python#16]

**Comment by gofilipa** [comment]
This is something that is covered in the Text Analysis workshop. Did you mean that we should also add it to the python workshop?

**Comment by kallewesterling** [comment]
I think I added this issue and #15 when I attended the January 2020 DRI. In that workshop, these were some things that came up during the workshop or things that I thought learners could benefit from knowing in the light of what we were doing. I wish I would have taken more notes in the description, though!

**Comment by gofilipa** [comment]
Ah I see! I do wonder if slice() is too complicated for the python course, though. It takes a couple of parameters, a start and end point, and we aren't working with very long lists at that moment. I also recall that Text Analysis workshop has slice already, so we could be covered there.

That being said, I do think that we should incorporate a few more functions that work with text manipulation and regularization. Maybe something like sort(), count(), append(), pop()? I'm also looking at ways to make the python workshop examples more relevant to text manipulation (see #28). Right now, I'm thinking about replacing the "weather app" section with a "library app" where participants sort and append a list of books (could be books from their own research). I think this will build well into the Text Analysis workshop.

I'd like to hear what you think, @kallewesterling and also @rafadavis, since he's revising the Text Analysis workshop.

**Comment by kallewesterling** [comment]
I didn't really mean the `slice()` function though (didn't actually even know it existed but that's cool!). I just meant simple list slicing using indexing:

```python
flowers = ['daisies', 'lilies', 'orchids', 'roses']
print(flowers[2:3])
```

I think, following list indexing, it would make sense to point out the slicing of lists can be done this way.

But yes, it might be good to point out that you can also do lots of other things with lists — `sort`, `append`, `pop` are great.

And I *love* the idea of a library app!

As for the `text-analysis` workshop, hm, yes.. It's a little strange how the two workshops are overlapping, and maybe we should all think a little bit further about how things can be teased out from each other. I feel like if we say that the `text-analysis` workshop requires for someone to have done the `python` workshop before, then we shouldn't necessarily repeat—or learn more!—Python in the `text-analysis` workshop. But things that are brought up in the `text-analysis` workshop should, conversely, also be part of the Python workshop. Am I right/making sense right now?

**Comment by gofilipa** [comment]
oh--I see what you mean! I added some text and practice with list slicing (using the method you suggested) to the section on list indexing. I think it goes nicely there, and it's a good time to also gesture that this will be picked up and expanded in the Text Analysis workshop. I'll push the changes soon so you can see them.

Thank you for the clarification. And yes, we should definitely catch up on potential overlaps and necessary prerequisites between Python and Text Analysis.

Going to close out this issue now.

**Comment by kallewesterling** [comment]
Looks great! Thanks!

(Sorry I only saw this now - I have been working so much on the website that I haven't kept up with the other repos!)
